#!/usr/bin/env python
# This file is part of plog.
#
# plog is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License.
#
# plog is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with plog.  If not, see <http://www.gnu.org/licenses/>.
#

import sys

# FIXME: Add installation prefix path to sys.path

def main():
    """
    Main routine, just loads and starts file2log main routine.
    """
    import plog.log2db.main

    plog.log2db.main.main()

if __name__ == '__main__':
   main()
